// Code generated by mockery v2.20.0. DO NOT EDIT.

package user

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetUserByPhoneNumber provides a mock function with given fields: ctx, phoneNumber
func (_m *MockRepository) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (*User, error) {
	ret := _m.Called(ctx, phoneNumber)

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return rf(ctx, phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = rf(ctx, phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserByPhoneNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPhoneNumber'
type MockRepository_GetUserByPhoneNumber_Call struct {
	*mock.Call
}

// GetUserByPhoneNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
func (_e *MockRepository_Expecter) GetUserByPhoneNumber(ctx interface{}, phoneNumber interface{}) *MockRepository_GetUserByPhoneNumber_Call {
	return &MockRepository_GetUserByPhoneNumber_Call{Call: _e.mock.On("GetUserByPhoneNumber", ctx, phoneNumber)}
}

func (_c *MockRepository_GetUserByPhoneNumber_Call) Run(run func(ctx context.Context, phoneNumber string)) *MockRepository_GetUserByPhoneNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserByPhoneNumber_Call) Return(_a0 *User, _a1 error) *MockRepository_GetUserByPhoneNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserByPhoneNumber_Call) RunAndReturn(run func(context.Context, string) (*User, error)) *MockRepository_GetUserByPhoneNumber_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t mockConstructorTestingTNewMockRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
