name: Bank Yaya Backend Service configurations
version: 1.0.0
configs:
  app:
    port: 3000
  postgres:
    dsn: "host=10.100.0.14 user=postgres password=DoBdkzEKqH0axsjs dbname=_supperapps port=5432 sslmode=disable TimeZone=Asia/Jakarta"
  corebanking:
    url: "http://172.16.31.93:8888"
    username: "superapps"
    password: "qKb365UykBd9vXpK"
  email:
    from: "noreply@bankyaya.co.id"
    host: "host"
    port: "123"
    username: "username"
    password: "password"
  token:
    secret: "_jwt_secret_"
    headerKid: "ID-001"
