// Code generated by mockery v2.20.0. DO NOT EDIT.

package securitymock

import mock "github.com/stretchr/testify/mock"

// SequenceGenerator is an autogenerated mock type for the SequenceGenerator type
type SequenceGenerator struct {
	mock.Mock
}

type SequenceGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *SequenceGenerator) EXPECT() *SequenceGenerator_Expecter {
	return &SequenceGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields:
func (_m *SequenceGenerator) Generate() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SequenceGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type SequenceGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *SequenceGenerator_Expecter) Generate() *SequenceGenerator_Generate_Call {
	return &SequenceGenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *SequenceGenerator_Generate_Call) Run(run func()) *SequenceGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SequenceGenerator_Generate_Call) Return(_a0 string, _a1 error) *SequenceGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SequenceGenerator_Generate_Call) RunAndReturn(run func() (string, error)) *SequenceGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewSequenceGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewSequenceGenerator creates a new instance of SequenceGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSequenceGenerator(t mockConstructorTestingTNewSequenceGenerator) *SequenceGenerator {
	mock := &SequenceGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
