// Code generated by mockery v2.53.3. DO NOT EDIT.

package intrabank

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCoreBanking is an autogenerated mock type for the CoreBanking type
type MockCoreBanking struct {
	mock.Mock
}

type MockCoreBanking_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoreBanking) EXPECT() *MockCoreBanking_Expecter {
	return &MockCoreBanking_Expecter{mock: &_m.Mock}
}

// GetAccountDetails provides a mock function with given fields: ctx, accountNumber
func (_m *MockCoreBanking) GetAccountDetails(ctx context.Context, accountNumber string) (*Account, error) {
	ret := _m.Called(ctx, accountNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountDetails")
	}

	var r0 *Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Account, error)); ok {
		return rf(ctx, accountNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Account); ok {
		r0 = rf(ctx, accountNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoreBanking_GetAccountDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountDetails'
type MockCoreBanking_GetAccountDetails_Call struct {
	*mock.Call
}

// GetAccountDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumber string
func (_e *MockCoreBanking_Expecter) GetAccountDetails(ctx interface{}, accountNumber interface{}) *MockCoreBanking_GetAccountDetails_Call {
	return &MockCoreBanking_GetAccountDetails_Call{Call: _e.mock.On("GetAccountDetails", ctx, accountNumber)}
}

func (_c *MockCoreBanking_GetAccountDetails_Call) Run(run func(ctx context.Context, accountNumber string)) *MockCoreBanking_GetAccountDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCoreBanking_GetAccountDetails_Call) Return(_a0 *Account, _a1 error) *MockCoreBanking_GetAccountDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoreBanking_GetAccountDetails_Call) RunAndReturn(run func(context.Context, string) (*Account, error)) *MockCoreBanking_GetAccountDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoreStatus provides a mock function with given fields: ctx
func (_m *MockCoreBanking) GetCoreStatus(ctx context.Context) (*CoreStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCoreStatus")
	}

	var r0 *CoreStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*CoreStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *CoreStatus); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CoreStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoreBanking_GetCoreStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoreStatus'
type MockCoreBanking_GetCoreStatus_Call struct {
	*mock.Call
}

// GetCoreStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCoreBanking_Expecter) GetCoreStatus(ctx interface{}) *MockCoreBanking_GetCoreStatus_Call {
	return &MockCoreBanking_GetCoreStatus_Call{Call: _e.mock.On("GetCoreStatus", ctx)}
}

func (_c *MockCoreBanking_GetCoreStatus_Call) Run(run func(ctx context.Context)) *MockCoreBanking_GetCoreStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCoreBanking_GetCoreStatus_Call) Return(_a0 *CoreStatus, _a1 error) *MockCoreBanking_GetCoreStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoreBanking_GetCoreStatus_Call) RunAndReturn(run func(context.Context) (*CoreStatus, error)) *MockCoreBanking_GetCoreStatus_Call {
	_c.Call.Return(run)
	return _c
}

// PerformOverbooking provides a mock function with given fields: ctx, req
func (_m *MockCoreBanking) PerformOverbooking(ctx context.Context, req *OverbookingInput) (*OverbookingResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PerformOverbooking")
	}

	var r0 *OverbookingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *OverbookingInput) (*OverbookingResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *OverbookingInput) *OverbookingResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*OverbookingResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *OverbookingInput) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoreBanking_PerformOverbooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PerformOverbooking'
type MockCoreBanking_PerformOverbooking_Call struct {
	*mock.Call
}

// PerformOverbooking is a helper method to define mock.On call
//   - ctx context.Context
//   - req *OverbookingInput
func (_e *MockCoreBanking_Expecter) PerformOverbooking(ctx interface{}, req interface{}) *MockCoreBanking_PerformOverbooking_Call {
	return &MockCoreBanking_PerformOverbooking_Call{Call: _e.mock.On("PerformOverbooking", ctx, req)}
}

func (_c *MockCoreBanking_PerformOverbooking_Call) Run(run func(ctx context.Context, req *OverbookingInput)) *MockCoreBanking_PerformOverbooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*OverbookingInput))
	})
	return _c
}

func (_c *MockCoreBanking_PerformOverbooking_Call) Return(_a0 *OverbookingResult, _a1 error) *MockCoreBanking_PerformOverbooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoreBanking_PerformOverbooking_Call) RunAndReturn(run func(context.Context, *OverbookingInput) (*OverbookingResult, error)) *MockCoreBanking_PerformOverbooking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCoreBanking creates a new instance of MockCoreBanking. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoreBanking(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoreBanking {
	mock := &MockCoreBanking{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
