// Code generated by mockery v2.53.3. DO NOT EDIT.

package intrabank

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReceiptMailer is an autogenerated mock type for the ReceiptMailer type
type MockReceiptMailer struct {
	mock.Mock
}

type MockReceiptMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceiptMailer) EXPECT() *MockReceiptMailer_Expecter {
	return &MockReceiptMailer_Expecter{mock: &_m.Mock}
}

// SendReceipt provides a mock function with given fields: ctx, data
func (_m *MockReceiptMailer) SendReceipt(ctx context.Context, data *EmailData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SendReceipt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *EmailData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReceiptMailer_SendReceipt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReceipt'
type MockReceiptMailer_SendReceipt_Call struct {
	*mock.Call
}

// SendReceipt is a helper method to define mock.On call
//   - ctx context.Context
//   - data *EmailData
func (_e *MockReceiptMailer_Expecter) SendReceipt(ctx interface{}, data interface{}) *MockReceiptMailer_SendReceipt_Call {
	return &MockReceiptMailer_SendReceipt_Call{Call: _e.mock.On("SendReceipt", ctx, data)}
}

func (_c *MockReceiptMailer_SendReceipt_Call) Run(run func(ctx context.Context, data *EmailData)) *MockReceiptMailer_SendReceipt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*EmailData))
	})
	return _c
}

func (_c *MockReceiptMailer_SendReceipt_Call) Return(_a0 error) *MockReceiptMailer_SendReceipt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReceiptMailer_SendReceipt_Call) RunAndReturn(run func(context.Context, *EmailData) error) *MockReceiptMailer_SendReceipt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReceiptMailer creates a new instance of MockReceiptMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceiptMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceiptMailer {
	mock := &MockReceiptMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
