// Code generated by mockery v2.20.0. DO NOT EDIT.

package intrabank

import mock "github.com/stretchr/testify/mock"

// MockSequenceGenerator is an autogenerated mock type for the SequenceGenerator type
type MockSequenceGenerator struct {
	mock.Mock
}

type MockSequenceGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSequenceGenerator) EXPECT() *MockSequenceGenerator_Expecter {
	return &MockSequenceGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields:
func (_m *MockSequenceGenerator) Generate() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSequenceGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockSequenceGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockSequenceGenerator_Expecter) Generate() *MockSequenceGenerator_Generate_Call {
	return &MockSequenceGenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockSequenceGenerator_Generate_Call) Run(run func()) *MockSequenceGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSequenceGenerator_Generate_Call) Return(_a0 string, _a1 error) *MockSequenceGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSequenceGenerator_Generate_Call) RunAndReturn(run func() (string, error)) *MockSequenceGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockSequenceGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockSequenceGenerator creates a new instance of MockSequenceGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockSequenceGenerator(t mockConstructorTestingTNewMockSequenceGenerator) *MockSequenceGenerator {
	mock := &MockSequenceGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
