// Code generated by mockery v2.20.0. DO NOT EDIT.

package messagingmock

import (
	context "context"

	entity "go.bankyaya.org/app/backend/internal/core/entity"

	mock "github.com/stretchr/testify/mock"
)

// ScheduledTransferProcessor is an autogenerated mock type for the ScheduledTransferProcessor type
type ScheduledTransferProcessor struct {
	mock.Mock
}

type ScheduledTransferProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *ScheduledTransferProcessor) EXPECT() *ScheduledTransferProcessor_Expecter {
	return &ScheduledTransferProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function with given fields: ctx, req
func (_m *ScheduledTransferProcessor) Process(ctx context.Context, req *entity.TransferRequest) error {
	ret := _m.Called(ctx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.TransferRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ScheduledTransferProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type ScheduledTransferProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.TransferRequest
func (_e *ScheduledTransferProcessor_Expecter) Process(ctx interface{}, req interface{}) *ScheduledTransferProcessor_Process_Call {
	return &ScheduledTransferProcessor_Process_Call{Call: _e.mock.On("Process", ctx, req)}
}

func (_c *ScheduledTransferProcessor_Process_Call) Run(run func(ctx context.Context, req *entity.TransferRequest)) *ScheduledTransferProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TransferRequest))
	})
	return _c
}

func (_c *ScheduledTransferProcessor_Process_Call) Return(_a0 error) *ScheduledTransferProcessor_Process_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScheduledTransferProcessor_Process_Call) RunAndReturn(run func(context.Context, *entity.TransferRequest) error) *ScheduledTransferProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewScheduledTransferProcessor interface {
	mock.TestingT
	Cleanup(func())
}

// NewScheduledTransferProcessor creates a new instance of ScheduledTransferProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScheduledTransferProcessor(t mockConstructorTestingTNewScheduledTransferProcessor) *ScheduledTransferProcessor {
	mock := &ScheduledTransferProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
