// Code generated by mockery v2.20.0. DO NOT EDIT.

package repomock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "go.bankyaya.org/app/backend/internal/core/entity"
)

// TransferRepository is an autogenerated mock type for the TransferRepository type
type TransferRepository struct {
	mock.Mock
}

type TransferRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TransferRepository) EXPECT() *TransferRepository_Expecter {
	return &TransferRepository_Expecter{mock: &_m.Mock}
}

// GetSequence provides a mock function with given fields: ctx, sequenceNumber
func (_m *TransferRepository) GetSequence(ctx context.Context, sequenceNumber string) (*entity.Sequence, error) {
	ret := _m.Called(ctx, sequenceNumber)

	var r0 *entity.Sequence
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Sequence, error)); ok {
		return rf(ctx, sequenceNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Sequence); ok {
		r0 = rf(ctx, sequenceNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Sequence)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sequenceNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferRepository_GetSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSequence'
type TransferRepository_GetSequence_Call struct {
	*mock.Call
}

// GetSequence is a helper method to define mock.On call
//   - ctx context.Context
//   - sequenceNumber string
func (_e *TransferRepository_Expecter) GetSequence(ctx interface{}, sequenceNumber interface{}) *TransferRepository_GetSequence_Call {
	return &TransferRepository_GetSequence_Call{Call: _e.mock.On("GetSequence", ctx, sequenceNumber)}
}

func (_c *TransferRepository_GetSequence_Call) Run(run func(ctx context.Context, sequenceNumber string)) *TransferRepository_GetSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TransferRepository_GetSequence_Call) Return(_a0 *entity.Sequence, _a1 error) *TransferRepository_GetSequence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferRepository_GetSequence_Call) RunAndReturn(run func(context.Context, string) (*entity.Sequence, error)) *TransferRepository_GetSequence_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: ctx, id
func (_m *TransferRepository) GetUserById(ctx context.Context, id int) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferRepository_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type TransferRepository_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TransferRepository_Expecter) GetUserById(ctx interface{}, id interface{}) *TransferRepository_GetUserById_Call {
	return &TransferRepository_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *TransferRepository_GetUserById_Call) Run(run func(ctx context.Context, id int)) *TransferRepository_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *TransferRepository_GetUserById_Call) Return(_a0 *entity.User, _a1 error) *TransferRepository_GetUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransferRepository_GetUserById_Call) RunAndReturn(run func(context.Context, int) (*entity.User, error)) *TransferRepository_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSequence provides a mock function with given fields: ctx, seq
func (_m *TransferRepository) InsertSequence(ctx context.Context, seq *entity.Sequence) error {
	ret := _m.Called(ctx, seq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Sequence) error); ok {
		r0 = rf(ctx, seq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferRepository_InsertSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSequence'
type TransferRepository_InsertSequence_Call struct {
	*mock.Call
}

// InsertSequence is a helper method to define mock.On call
//   - ctx context.Context
//   - seq *entity.Sequence
func (_e *TransferRepository_Expecter) InsertSequence(ctx interface{}, seq interface{}) *TransferRepository_InsertSequence_Call {
	return &TransferRepository_InsertSequence_Call{Call: _e.mock.On("InsertSequence", ctx, seq)}
}

func (_c *TransferRepository_InsertSequence_Call) Run(run func(ctx context.Context, seq *entity.Sequence)) *TransferRepository_InsertSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Sequence))
	})
	return _c
}

func (_c *TransferRepository_InsertSequence_Call) Return(_a0 error) *TransferRepository_InsertSequence_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransferRepository_InsertSequence_Call) RunAndReturn(run func(context.Context, *entity.Sequence) error) *TransferRepository_InsertSequence_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransaction provides a mock function with given fields: ctx, transaction
func (_m *TransferRepository) InsertTransaction(ctx context.Context, transaction *entity.Transaction) error {
	ret := _m.Called(ctx, transaction)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferRepository_InsertTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransaction'
type TransferRepository_InsertTransaction_Call struct {
	*mock.Call
}

// InsertTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *entity.Transaction
func (_e *TransferRepository_Expecter) InsertTransaction(ctx interface{}, transaction interface{}) *TransferRepository_InsertTransaction_Call {
	return &TransferRepository_InsertTransaction_Call{Call: _e.mock.On("InsertTransaction", ctx, transaction)}
}

func (_c *TransferRepository_InsertTransaction_Call) Run(run func(ctx context.Context, transaction *entity.Transaction)) *TransferRepository_InsertTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Transaction))
	})
	return _c
}

func (_c *TransferRepository_InsertTransaction_Call) Return(_a0 error) *TransferRepository_InsertTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransferRepository_InsertTransaction_Call) RunAndReturn(run func(context.Context, *entity.Transaction) error) *TransferRepository_InsertTransaction_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewTransferRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransferRepository creates a new instance of TransferRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransferRepository(t mockConstructorTestingTNewTransferRepository) *TransferRepository {
	mock := &TransferRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
