// Code generated by mockery v2.20.0. DO NOT EDIT.

package repomock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "go.bankyaya.org/app/backend/internal/core/entity"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetDeviceById provides a mock function with given fields: ctx, deviceId
func (_m *UserRepository) GetDeviceById(ctx context.Context, deviceId string) (*entity.Device, error) {
	ret := _m.Called(ctx, deviceId)

	var r0 *entity.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Device, error)); ok {
		return rf(ctx, deviceId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Device); ok {
		r0 = rf(ctx, deviceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deviceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserDataByPhoneNumber provides a mock function with given fields: ctx, phoneNumber
func (_m *UserRepository) GetUserDataByPhoneNumber(ctx context.Context, phoneNumber string) (*entity.User, error) {
	ret := _m.Called(ctx, phoneNumber)

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
