// Code generated by mockery v2.20.0. DO NOT EDIT.

package apimock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "go.bankyaya.org/app/backend/internal/core/entity"
)

// CoreBanking is an autogenerated mock type for the CoreBanking type
type CoreBanking struct {
	mock.Mock
}

type CoreBanking_Expecter struct {
	mock *mock.Mock
}

func (_m *CoreBanking) EXPECT() *CoreBanking_Expecter {
	return &CoreBanking_Expecter{mock: &_m.Mock}
}

// CheckEOD provides a mock function with given fields: ctx
func (_m *CoreBanking) CheckEOD(ctx context.Context) (*entity.EODData, error) {
	ret := _m.Called(ctx)

	var r0 *entity.EODData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entity.EODData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entity.EODData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.EODData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreBanking_CheckEOD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckEOD'
type CoreBanking_CheckEOD_Call struct {
	*mock.Call
}

// CheckEOD is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CoreBanking_Expecter) CheckEOD(ctx interface{}) *CoreBanking_CheckEOD_Call {
	return &CoreBanking_CheckEOD_Call{Call: _e.mock.On("CheckEOD", ctx)}
}

func (_c *CoreBanking_CheckEOD_Call) Run(run func(ctx context.Context)) *CoreBanking_CheckEOD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CoreBanking_CheckEOD_Call) Return(_a0 *entity.EODData, _a1 error) *CoreBanking_CheckEOD_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreBanking_CheckEOD_Call) RunAndReturn(run func(context.Context) (*entity.EODData, error)) *CoreBanking_CheckEOD_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountDetails provides a mock function with given fields: ctx, accountNumber
func (_m *CoreBanking) GetAccountDetails(ctx context.Context, accountNumber string) (*entity.AccountDetails, error) {
	ret := _m.Called(ctx, accountNumber)

	var r0 *entity.AccountDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.AccountDetails, error)); ok {
		return rf(ctx, accountNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.AccountDetails); ok {
		r0 = rf(ctx, accountNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AccountDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreBanking_GetAccountDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountDetails'
type CoreBanking_GetAccountDetails_Call struct {
	*mock.Call
}

// GetAccountDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNumber string
func (_e *CoreBanking_Expecter) GetAccountDetails(ctx interface{}, accountNumber interface{}) *CoreBanking_GetAccountDetails_Call {
	return &CoreBanking_GetAccountDetails_Call{Call: _e.mock.On("GetAccountDetails", ctx, accountNumber)}
}

func (_c *CoreBanking_GetAccountDetails_Call) Run(run func(ctx context.Context, accountNumber string)) *CoreBanking_GetAccountDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CoreBanking_GetAccountDetails_Call) Return(_a0 *entity.AccountDetails, _a1 error) *CoreBanking_GetAccountDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreBanking_GetAccountDetails_Call) RunAndReturn(run func(context.Context, string) (*entity.AccountDetails, error)) *CoreBanking_GetAccountDetails_Call {
	_c.Call.Return(run)
	return _c
}

// PerformOverbooking provides a mock function with given fields: ctx, req
func (_m *CoreBanking) PerformOverbooking(ctx context.Context, req *entity.OverbookingRequest) (*entity.OverbookingResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *entity.OverbookingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OverbookingRequest) (*entity.OverbookingResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OverbookingRequest) *entity.OverbookingResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OverbookingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.OverbookingRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoreBanking_PerformOverbooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PerformOverbooking'
type CoreBanking_PerformOverbooking_Call struct {
	*mock.Call
}

// PerformOverbooking is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entity.OverbookingRequest
func (_e *CoreBanking_Expecter) PerformOverbooking(ctx interface{}, req interface{}) *CoreBanking_PerformOverbooking_Call {
	return &CoreBanking_PerformOverbooking_Call{Call: _e.mock.On("PerformOverbooking", ctx, req)}
}

func (_c *CoreBanking_PerformOverbooking_Call) Run(run func(ctx context.Context, req *entity.OverbookingRequest)) *CoreBanking_PerformOverbooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.OverbookingRequest))
	})
	return _c
}

func (_c *CoreBanking_PerformOverbooking_Call) Return(_a0 *entity.OverbookingResponse, _a1 error) *CoreBanking_PerformOverbooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CoreBanking_PerformOverbooking_Call) RunAndReturn(run func(context.Context, *entity.OverbookingRequest) (*entity.OverbookingResponse, error)) *CoreBanking_PerformOverbooking_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewCoreBanking interface {
	mock.TestingT
	Cleanup(func())
}

// NewCoreBanking creates a new instance of CoreBanking. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCoreBanking(t mockConstructorTestingTNewCoreBanking) *CoreBanking {
	mock := &CoreBanking{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
