// Code generated by mockery v2.20.0. DO NOT EDIT.

package usermock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	user "go.bankyaya.org/app/backend/internal/domain/user"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetUserByPhoneNumber provides a mock function with given fields: ctx, phoneNumber
func (_m *Repository) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (*user.User, error) {
	ret := _m.Called(ctx, phoneNumber)

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, phoneNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, phoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phoneNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetUserByPhoneNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPhoneNumber'
type Repository_GetUserByPhoneNumber_Call struct {
	*mock.Call
}

// GetUserByPhoneNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - phoneNumber string
func (_e *Repository_Expecter) GetUserByPhoneNumber(ctx interface{}, phoneNumber interface{}) *Repository_GetUserByPhoneNumber_Call {
	return &Repository_GetUserByPhoneNumber_Call{Call: _e.mock.On("GetUserByPhoneNumber", ctx, phoneNumber)}
}

func (_c *Repository_GetUserByPhoneNumber_Call) Run(run func(ctx context.Context, phoneNumber string)) *Repository_GetUserByPhoneNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_GetUserByPhoneNumber_Call) Return(_a0 *user.User, _a1 error) *Repository_GetUserByPhoneNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetUserByPhoneNumber_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *Repository_GetUserByPhoneNumber_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
